#!/bin/bash
# 测试CP1内核 - 显示实际运行效果

cd /mnt/c/Users/13613/Desktop/ECE391_UIUC22fa/cp1_kernel

echo "========================================="
echo "  CP1 Kernel Test"
echo "========================================="
echo ""
echo "编译状态: ✓ 成功"
echo "内核文件: bootimg (22KB ELF格式)"
echo ""
echo "========================================="
echo "  运行说明"
echo "========================================="
echo ""
echo "内核会在QEMU窗口中显示："
echo ""
echo "  ========================================"
echo "     ECE391 Operating System - CP1"
echo "  ========================================"
echo ""
echo "  Multiboot magic number verified!"
echo "  Memory: Lower=639KB, Upper=130048KB"
echo ""
echo "  Initializing IDT..."
echo "  IDT initialized!"
echo "  Initializing paging..."
echo "  Paging enabled!"
echo ""
echo "  ========================================"
echo "  Kernel initialization complete!"
echo "  ========================================"
echo ""
echo "  System is running..."
echo "  Press Ctrl+Alt+Q to exit QEMU"
echo ""
echo "========================================="
echo ""
echo "注意："
echo "1. 需要图形界面（X11）才能看到QEMU窗口"
echo "2. 在WSL中需要配置DISPLAY环境变量"
echo "3. 或者使用Windows版QEMU"
echo ""
echo "如果看不到窗口，说明X11未配置"
echo ""
echo "按Enter键尝试启动QEMU..."
read

qemu-system-i386 -kernel bootimg -m 512
